#ifndef BOARD_BLE_H
#define BOARD_BLE_H

#define ENABLE_RDYN_INT()  ROM_GPIOIntEnable(BLE_RDYN_PIN, BLE_RDYN_PIN_INT);
#define DISABLE_RDYN_INT() ROM_GPIOIntDisable(BLE_RDYN_PIN, BLE_RDYN_PIN_INT);

#define SET_REQN_LOW()  ROM_GPIOPinWrite(BLE_REQN_PORTBASE, BLE_REQN_PIN, 0);
#define SET_REQN_HIGH() ROM_GPIOPinWrite(BLE_REQN_PORTBASE, BLE_REQN_PIN, BLE_REQN_PIN);

#endif //BOARD_BLE_H